---
# Add nginx repo & install
- name: Create repo for nginx
  ansible.builtin.copy:
    src: ./nginx.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Install nginx & unzip
  ansible.builtin.yum:
    name: "nginx"
    state: present

- name: Create nginx config (default)
  ansible.builtin.template:
    src: "nginx_light.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    force: yes
